# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alagar biotech
email: alagarbioteches091@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This theme is based on the Business Jekyll theme designed by 
  Melvin Ch'ng. See [Business Jekyll theme](https://github.com/melvinchng/business-jekyll-theme/blob/master/README.md).
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Alagar Biotech Product Pvt Ltd
address_line: 3/310, Raja Badar St, Nainarkuppam, Chennai, Tamil Nadu 600119
Whatsapp number: 9498402214
company_email: alagarbioteches091@gmail.com
google_map: https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d3618.727010735933!2d91.837871!3d24.907291700000002!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2s!4v1404919738144

# Social Link
facebook_link: http://www.facebook.com
X_link: https://x.com/alagarbiotech
linkedin_link: http://www.linkedin.com
review_link: https://g.page/r/CWne1A2RNyGoEBM/review

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
